### ISSUE TITLE
Add eslint v6.0 as peer dependency

### ISSUE THREAD

**Issue by borestad** [SonarSource/eslint-plugin-sonarjs#120]
**I want to request a feature.**

Please bump support for eslint 6.0. I've been using it internally for several weeks, and it seems to work fine.

**Comment by andrea-guarino-sonarsource** [comment]
Hi @borestad,
Thanks for your tests!
Currently we're not working on our JavaScript analizer, but we should have a sprint pretty soon.
We'll need to go through breaking changes listed [here](https://eslint.org/docs/user-guide/migrating-to-6.0.0) and release a new version of `eslint-plugin-sonarjs`.
