### ISSUE TITLE
sonarjs/no-duplicate-string thrown for 'use strict'

### ISSUE THREAD

**Issue by diegocr** [SonarSource/eslint-plugin-sonarjs#127]
The rule `sonarjs/no-duplicate-string` should be ignored for `'use strict';` statements, please!

**Comment by vilchik-elena** [comment]
as far as I know only one `'use strict';` is required per file. Why do you have more?

**Comment by diegocr** [comment]
I think that is something a plugin like this one should not assume, they can be globally (per file, as you said), or per-function.

In our project the requirement is per-function, and while we could wrap our code within an IIFE closure that is something not desirable

Moreover, the same applies to `'use asm';` or `'almost asm';` statements, these are required to be per-function, and therefore this plugin neither should complain about them.
