### ISSUE TITLE
Enhacement for `sonarjs/no-duplicate-string`

### ISSUE THREAD

**Issue by sabdol** [SonarSource/eslint-plugin-sonarjs#148]
I found out that `sonarjs/no-duplicate-string` is not really works well due to it suggest to avoid using same strings through whole file not by functional scope. So when I use same string on one file on different functions, it suggest me to make variable on top level of file and often the top level becomes global, which I do not want to make string variable to annoys it. I think it is good to add configurable options to make is only prevent duplicate strings within functional scope.

**Comment by vilchik-elena** [comment]
since ES modules are used by most projects, having a variable declared on the top level does not make it global. So I doubt that the enhancement you are suggesting worths it.
