### ISSUE TITLE
Rule: S1874 Deprecation request

### ISSUE THREAD

**Issue by gund** [SonarSource/eslint-plugin-sonarjs#150]
**I want to request a feature.**

Hi, I'm using `eslint` with `@typescript-eslint/eslint-plugin` and `eslint-plugin-sonarjs` plugins.

I would like to ask if there is any plans on bringing the rule S1874 Deprecation that was implemented a while ago in https://github.com/SonarSource/SonarJS/pull/1715 ?

I tried it to use on latest version of `eslint-plugin-sonarjs@0.5.0` but the rule is not there.

**Rule key:** S1874

**Comment by gund** [comment]
For anyone who is looking to use this rule now - I've ported it to separate plugin: https://github.com/gund/eslint-plugin-deprecation

**Comment by xiaoxiangmoe** [comment]
@yassin-kammoun-sonarsource any update on this?

**Comment by vilchik-elena** [comment]
We are considering contributing this rule to typescript-eslint plugin so closing this issue as won't fix
