### ISSUE TITLE
"Sonar way" or "Sonar way recommended"

### ISSUE THREAD

**Issue by tfdev** [SonarSource/eslint-plugin-sonarjs#152]
Hello guys,

After reading the readme file, it is not clear:

Does  ``` "plugin:sonarjs/recommended" ``` correspond to the ["Sonar way recommended" profile](https://sonarcloud.io/organizations/opensource/quality_profiles/show?language=js&name=Sonar+way+Recommended)?

Thanks for your reply

**Comment by vilchik-elena** [comment]
it basically does (still we don't guarantee that), but you should understand that `eslint-plugin-sonarjs` contains only subset of rules available on sonarcloud.io.

**Comment by wslyvh** [comment]
It doesn't seem to include code smells. Is it possible to add, or configure these?

**Comment by vilchik-elena** [comment]
@wslyvh We plan to do it eventually, but no big ambitions. SonarQube is our main project, we mainly invest there. 

FYI there is SonarLint - extension for IDE which can connect to SonarQube/SonarCloud, if by local dev env you mean that.

**Comment by vilchik-elena** [comment]
If any further concerns, please consider https://community.sonarsource.com/

Closing the issue
