### ISSUE TITLE
Sonarlint needed if using ESLint?

### ISSUE THREAD

**Issue by basickarl** [SonarSource/eslint-plugin-sonarjs#157]
I have a quick question, it's regarding the ESLint plugin versus the sonarlint vscode plugin. 

Do they do the same thing or does one do something that the other does not?

Sonarlint:
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode

For that to work you need Java and a scanner locally, I'm just trying to figure out if it is needed or worth it!

**Comment by saberduck** [comment]
sonarlint allows connected mode to synchronize your rules with SonarQube https://www.sonarlint.org/bring-your-team-on-board.  There are also some rules not currently available in eslint plugin.

**Comment by basickarl** [comment]
@saberduck So if using SonarLint I will not need the ESLint plugin? Is this what you are saying?

**Comment by peresbruno** [comment]
I have the same doubt.

**Comment by saberduck** [comment]
Yes, SonarLint is completely standalone. Additionally, it can analyze also Java, PHP, Python, and many other languages.

**Comment by Timoteus78** [comment]
My workflow is to run a  verify task before pushing which includes lint and unit tests. I would be great if a sonar scan could be included in that. Unfortunately it is not possible. If eslint could synchronize with the rules on our SQ server that would be the best of both world.

**Comment by rijans** [comment]
In my experience, you can (probably should) keep both. Even Sonarlint shows me some cool and complex suggestions, that ESLint cant!

**Comment by KerickHowlett** [comment]
I have a question that fits well into this topic: My SonarLint will highlight issues when it detects secrets (i.e. passwords or API keys).

My ESLint doesn't appear to be highlighting this, though.

Is there a specific rule I have to enable to check to also scan for secrets? Or is the plugin (or even ESLint in general) incapable of that?

**Comment by vilchik-elena** [comment]
@KerickHowlett Secrets is a SonarLint feature, I am not sure if there are ESLint alternatives

**Comment by Amitparsaniya** [comment]
@vilchik-elena i think SonarLInt is tool with that ,we can  define esLint rules and validate the code
