### ISSUE TITLE
Support ESLint 7x

### ISSUE THREAD

**Issue by GuillaumeRahbari** [SonarSource/eslint-plugin-sonarjs#162]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

Is it planned to have official ESLint 7 support ?

**Comment by silverwind** [comment]
I tried it in https://github.com/SonarSource/eslint-plugin-sonarjs/pull/163 but it looks the upgrade is more involved because of the typescript setup but I have no experience/motivation to dig deeper.

**Comment by vadimyen** [comment]
It will be great, cuz the plugin is extremely useful, but the last release was long time ago. Maybe, there're alternatives?

**Comment by silverwind** [comment]
Eslint 7 among other things is in https://github.com/SonarSource/eslint-plugin-sonarjs/pull/155.

**Comment by sanket-work** [comment]
Does this support eslint 7 or not ?

**Comment by softwarespot** [comment]
As mentioned in the merge request, this is currently a blocker for those who wish to upgrade to v15

**Comment by crystalfp** [comment]
Yes, please! The plugin is extremely useful as is the upgrade to node 15. For now I installed my project with the `--force` flag hoping for the best.

**Comment by johanbook** [comment]
Same here, support for 7.x would be greatly appreciated :pray:

**Comment by brettz9** [comment]
Implemented in fork at https://github.com/es-joy/eslint-plugin-radar

**Comment by crystalfp** [comment]
Exchanged `eslint-plugin-sonarjs` with `eslint-plugin-radar` with great satisfaction. Thanks!

**Comment by yassin-kammoun-sonarsource** [comment]
Fixed with #194

**Comment by Zialus** [comment]
@yassin-kammoun-sonarsource will version 0.6.0 be published soon?

**Comment by yassin-kammoun-sonarsource** [comment]
@Zialus It is published now ;)

**Comment by J3m5** [comment]
> Exchanged `eslint-plugin-sonarjs` with `eslint-plugin-radar` with great satisfaction. Thanks!

Looks like we should get back to sonarjs now that radar has gone unmaintained @crystalfp

**Comment by crystalfp** [comment]
@J3m5 Thanks for alerting me. I returned to `eslint-plugin-sonarjs` and have no more problems so far.
Thanks to all!
