### ISSUE TITLE
Add config with severity "warn"

### ISSUE THREAD

**Issue by micaelmbagira** [SonarSource/eslint-plugin-sonarjs#166]
**I want to request a feature.**

It would be great to have a preset config such as `plugin:sonarjs/warn` where the severity is `warn` instead of `error`.  
When enabling this plugin for the first time on a big project, it could block the CI/CD process. I believe one cannot always fix all the errors at once. I personally would like to have the warnings and later on, fix all errors. Does that make sense?

**Comment by vegerot** [comment]
This would be nice

**Comment by vilchik-elena** [comment]
btw feel free to try [sonarcloud](https://sonarcloud.io/) (it's reporting issues from this plugin as well). There you will see only "new" issues (check here https://blog.sonarsource.com/clean-as-you-code)

**Comment by vilchik-elena** [comment]
I wonder if other plugins doing something similar, @micaelmbagira could you share some examples?

**Comment by micaelmbagira** [comment]
@vilchik-elena quite sure I've seen it somewhere else when I was looking into it but I can't remember...

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-5](https://sonarsource.atlassian.net/browse/ESLINTJS-5)
