### ISSUE TITLE
Is there a way to exclude folders for just the plugin?

### ISSUE THREAD

**Issue by KeithPepin** [SonarSource/eslint-plugin-sonarjs#167]
**I want to request a feature.**

I would like to be able to exclude certain folders from the sonarjs rules entirely when running eslint (test folders for example). Is there a way to configure the plugin so that it doesn't come into play for certain directories?

**Comment by vilchik-elena** [comment]
You better check that with eslint

**Comment by brettz9** [comment]
You can set separate config for certain files using `overrides`; see https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files .

While you can disable individual rules within `overrides` or extend from another config (e.g., one which disables all of the sonarjs rules), AFAICT, to bulk disable you'd have to use https://www.npmjs.com/package/eslint-plugin-disable . But you could workaround this apparent lack of bulk disabling by only having your sonarjs rules inside of an `overrides` which targets the files where you *do* want them applied (optionally using other `overrides` for linting your test files with test-specific linting, e.g., `eslint-plugin-mocha`, the Chai plugins, etc.).
