### ISSUE TITLE
sonarjs/no-duplicate-string to strict for css values

### ISSUE THREAD

**Issue by vdhpieter** [SonarSource/eslint-plugin-sonarjs#173]
**I want to request a feature.**

While running the plugin we got an error about `boxSizing: 'border-box',` because the border-box string was duplicated in 3 places in the file. We don't want to put CSS values in variables. Could an ignore list be added to the plugin to add these kind of values?

**Comment by vilchik-elena** [comment]
the point of the rule is that it's easy to do a typo and it's safer to reuse a constant. Don't you think that this reasoning is relevant even in your use case?

**Comment by vdhpieter** [comment]
I get the point but in this specific use case we would define a constant for all css values that are strings and create them in every file or create them in a config file and import that in every `.tsx` file. That's a lot of work for just using CSS in frontend components...
