### ISSUE TITLE
Bump eslint dependency to v7

### ISSUE THREAD

**Issue by alvis** [SonarSource/eslint-plugin-sonarjs#183]
Currently `eslint-plugin-sonarjs` declares a peer dependency with `eslint` up to v6.
However, `eslint` has released v7 a while ago and we should add it.

Previously with npm v6, my projects used it with eslint v7 without any problem except for the warning message from npm.
Now with npm v7, the peer dependencies installation would fail since it now sees it as a conflict...

Sorry. Just saw #162.

**Comment by brettz9** [comment]
Implemented in fork at https://github.com/es-joy/eslint-plugin-radar  . And for the maintainers here, yes, this is a dupe.

**Comment by yassin-kammoun-sonarsource** [comment]
Fixed with #194
