### ISSUE TITLE
Exclude constructors from sonarjs/no-identical-functions

### ISSUE THREAD

**Issue by sfabriece** [SonarSource/eslint-plugin-sonarjs#189]
**I want to request a feature.**

Sometimes, we can have identical constructors for different functionality. As far as I know, we can't abstract the parameters of a constructor.

It would be great if there was an option to exclude constructors from `sonarjs/no-identical-functions`

**Comment by vilchik-elena** [comment]
Hi, 

Sorry for a big delay. Could you share an example of the case you believe should not be reported?

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-10](https://sonarsource.atlassian.net/browse/ESLINTJS-10)
