### ISSUE TITLE
License concern

### ISSUE THREAD

**Issue by brettz9** [SonarSource/eslint-plugin-sonarjs#190]
@saberduck 

Per https://spdx.org/licenses/ , the (non-deprecated) format to be used in `license` of `package.json`, the valid identifiers for LGPL3 are `LGPL-3.0-only` or `LGPL-3.0-or-later`. Since neither "or later" or "or any later version" seemed to be mentioned anywhere (besides the license speaking to the possibility the license could be stated as being such, I wanted to confirm the license is indeed meant to be `LGPL-3.0-only` and not `LGPL-3.0-or-later` (so I could update our fork).

If you're not sure, I guess the safest option for us is `LGPL-3.0-only`.

Thanks!

**Comment by brettz9** [comment]
On the other hand, the license headers you have seem to indicate "or later" is ok.

**Comment by saberduck** [comment]
Project is licensed under the license in `LICENSE` file in the root of the repo. I will update the `package.json` to have `LGPL-3.0-only`

**Comment by brettz9** [comment]
Great, thanks. I am also planning to merge this branch (diffs at https://github.com/es-joy/eslint-plugin-radar/compare/master...brettz9:license ) so that the license header:

1. Reflects the "only" status of the license (so that users do not get confused and so that our project is not misrepresenting the actual license)
2. Aligns the punctuation and pointing to the FSF website instead of mailing address as per current suggested header conventions.

Please let me know if you see any problems with this. Thanks!

**Comment by Jiralite** [comment]
> Project is licensed under the license in `LICENSE` file in the root of the repo. I will update the `package.json` to have `LGPL-3.0-only`

It doesn't look like this happened, @saberduck?
