### ISSUE TITLE
Configure sonarjs/no-duplicate-string rule: add whitelist option

### ISSUE THREAD

**Issue by amankkg** [SonarSource/eslint-plugin-sonarjs#191]
**I want to request a feature.**

Option to whitelist some string constants for `sonarjs/no-duplicate-string`.

Use case: we have input type `datetime-local` defined multiple times per form, not in JSX but in plain objects representing a shape of a form (in order to generate actual form markup).

**Comment by PupoSDC** [comment]
same issue when writing React-native styles with strings such as `flex-start`

**Comment by vilchik-elena** [comment]
closing this issue in favor of #227
