### ISSUE TITLE
Improve prefer-while: ignore 'for' without condition

### ISSUE THREAD

**Issue by foxfriends** [SonarSource/eslint-plugin-sonarjs#196]
**I want to request a feature.**

When I write an infinite loop, I want to write `for (;;) {}`, but `prefer-while` gets flagged, forcing me to instead write `while (true)` but then another linter says "no constant conditions" and I'm back to the for loop.

Could an option for `prefer-while` be added that allows the infinite for loop to be used?

**Comment by Loxos** [comment]
Changing the behaviour of `prefer-while` to actually prefer a specific for loop which only has a condition seems counter-intuitive to me.

Especially as [no-constant-condition](https://eslint.org/docs/rules/no-constant-condition) already has an option to ignore constant conditions in loops.

The following settings should allow you to use `while(true){...}` and `do{...}while(true)`:

`no-constant-condition: ["error", { "checkLoops": false }]`

**Comment by foxfriends** [comment]
I would think it's more like allowing empty for, rather than preferring empty for. Same feel as any exception to other eslint rules. The empty for loop is also not so much "a specific for loop which only has a condition" but rather a for loop without a condition? Since a while loop cannot be without a condition, this is a special ability of the for loop that I would like to allow.

While ignoring constant conditions in loops is an option that allows writing an infinite loop, there is still no way to write the infinite for loop without disabling something.

**Comment by vilchik-elena** [comment]
I agree rule should not trigger if `for` does not have a condition, the purpose of the rule is to use `while(condition)` when only condition is defined for `for`.
