### ISSUE TITLE
Plugin being released with prerelease versions

### ISSUE THREAD

**Issue by aarongoldenthal** [SonarSource/eslint-plugin-sonarjs#223]
**I want to report a bug.**

The last three versions of this plugin (`0.7.1-116`, `0.7.1-117`, `0.8.0-125`) were released with version numbers indicating a prerelease version according to the [semver spec](https://semver.org/), which specifies that a `-` after the patch number indicates a prerelease version.  Since they were released under the `latest` tag, and after reviewing the commit messages, it does not appear that they were intended to be released as prerelease versions.

If they were intended to be installed as prerelease, they should not be tagged as `latest` since `npm install` by default installs the `latest` tag.

If they were not intended to be prerelease, in addition to the confusion, this causes issues with tools used to identify and update dependencies since most work off the version and will not update to these versions without specifically pinning the prerelease version.

**Comment by saberduck** [comment]
hello @aarongoldenthal,

indeed, it seems we don't follow the semver now, sorry for the issues. We will try to fix it in our build pipeline in the future release
