### ISSUE TITLE
Minimum required functions line of rule `no-identical-functions` can be configured

### ISSUE THREAD

**Issue by kamilic** [SonarSource/eslint-plugin-sonarjs#225]
**I want to request a feature.**
Hello.
I want a feature that the minimum required functions line of rule `no-identical-functions` can be configured by user.
Now is a fixed value 2.
https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/src/rules/no-identical-functions.ts#L66

I can contribute to this feature if need any helps.

**Comment by vilchik-elena** [comment]
Hi,
Could you explain why do you need this feature? Do you think 2 is too small or big?

**Comment by kamilic** [comment]
> Hi,
> Could you explain why do you need this feature? Do you think 2 is too small or big?

Thanks for your reply.

I think it is too small. 
In my situations, like writing some short and identical callback functions that will become different in future. Our developer just want to copy these identical callback as a "placeholder" for future modification.
To be honest, It does break the rule and need to be extracted as a global / local variables and not a best practice, but it sometime makes people feel bored, because they need to write an anothor function and delete the extracted variables rather than modified the "placeholder" directly.

**Comment by kamilic** [comment]
@vilchik-elena any ideas? If this is not the correct use cases please close this issue :).

**Comment by vilchik-elena** [comment]
@kamilic I would recommend to disable the issue for this particular case when you have a "placeholder". Having a bigger value for this parameter might hide from you other valid duplications.
