### ISSUE TITLE
Version 0.9.0 not published to npm

### ISSUE THREAD

**Issue by Anuovec** [SonarSource/eslint-plugin-sonarjs#258]
It is released in GitHub, but not published to npm and action si failed:
https://github.com/SonarSource/eslint-plugin-sonarjs/actions/runs/994180671

**Comment by vilchik-elena** [comment]
yeah-yeah, I know :) gonna work on that tomorrow, sorry for that!

**Comment by vilchik-elena** [comment]
done!
