### ISSUE TITLE
Missed `@typescript-eslint/experimental-utils` dependency

### ISSUE THREAD

**Issue by zloirock** [SonarSource/eslint-plugin-sonarjs#259]
After updating `eslint-plugin-sonarjs` to `0.9.0` on linting I see:
```
Error: Failed to load plugin 'sonarjs' declared in '.eslintrc.js': Cannot find module '@typescript-eslint/experimental-utils'
```

**Comment by jansepke** [comment]
Also typescript seems to be required which was not the case in the previous version

`Error: Failed to load plugin 'sonarjs' declared in '.eslintrc.js': Cannot find module 'typescript'`

**Comment by zloirock** [comment]
@jansepke in my case, adding `@typescript-eslint/experimental-utils` to dependencies is enough as a temporal fix.

**Comment by zloirock** [comment]
However, yes, seems `typescript` is loaded in [`no-ignored-return` rule](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/54dbe24849267d5ffc87ea5d1a97118b6cfed669/src/rules/no-ignored-return.ts#L22).

**Comment by cenfun** [comment]
same problem:
Oops! Something went wrong! :(

ESLint: 7.30.0

Error: Failed to load plugin 'sonarjs' declared in '--config': Cannot find module '@typescript-eslint/experimental-utils'
Require stack:
- node_modules/eslint-plugin-sonarjs/lib/utils/nodes.js
- node_modules/eslint-plugin-sonarjs/lib/rules/cognitive-complexity.js
- node_modules/eslint-plugin-sonarjs/lib/index.js
- node_modules/@eslint/eslintrc/lib/config-array-factory.js
- node_modules/@eslint/eslintrc/lib/index.js
-node_modules/slint/lib/cli-engine/cli-engine.js
- node_modules/eslint/lib/eslint/eslint.js
- node_modules/eslint/lib/eslint/index.js
- node_modules/eslint/lib/cli.js
-node_modules/eslint/bin/eslint.js


module @typescript-eslint/experimental-utils should be in dependencies not devDependencies
