### ISSUE TITLE
Error: Failed to load plugin 'sonarjs' declared in '..\.eslintrc.json': Cannot find module 'typescript'

### ISSUE THREAD

**Issue by creage** [SonarSource/eslint-plugin-sonarjs#265]
**I want to report a bug.**
Upgrading to 0.9.0 fails to lint in ES6 project, as your rules require `typescript` now, and it is not in your `dependencies`.

**eslint-plugin-sonarjs version:** 0.9.0<br>
**eslint version:** 7.30.0<br>
**Node.js version:** 14.17.1<br>

**Rule key:** no-ignored-return

**Comment by vilchik-elena** [comment]
bug fix is on its way!
