### ISSUE TITLE
Migrate our code to `import type` and enable rule `import/no-extraneous-dependencies`

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/eslint-plugin-sonarjs#266]
One could mistakenly use a devDependency in the production code. That will result in a runtime error as dependency will not be available. Note that it's ok to use devDependency for type declaration. 

In default configuration the rule might be activated on all non-test files (with `override` option).

Inspired by the problem we had after release version 0.9.0: #265, #259, so we should not postponing this rule to be able to activate it for ourself.

**Comment by EvgenyOrekhov** [comment]
This is already covered by [`import/no-extraneous-dependencies`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md).

**Comment by vilchik-elena** [comment]
@EvgenyOrekhov it is not. In our case it's ok to import devDependency for type declaration (in TypeScript) as it will be removing during transpilation.

**Comment by EvgenyOrekhov** [comment]
I believe `import/no-extraneous-dependencies` handles your case as well. It ignores type imports from `devDependencies`.

See this test: https://github.com/import-js/eslint-plugin-import/blob/95e60112bcb116c14f18005c42adf3d3e4501b32/tests/src/rules/no-extraneous-dependencies.js#L392-L398.

I tried it on one of my TypeScript projects, seems to be working as you described.

**Comment by vilchik-elena** [comment]
The rule is working if it is a `import type`, but one could use a regular import for type declaration. I agree for our needs we might migrate all those imports to `import type` and use the rule (and we indeed should do this!). But if we are thinking about wider audience, I wonder if every project will be fine with such migration. Wdyt? 
May be we could contribute to this rule and not report on regularly imported dev dependency if it's used only for type declaration.

**Comment by EvgenyOrekhov** [comment]
Oh, I see! Thanks for the explanation!

Since there is **autofixable** [`@typescript-eslint/consistent-type-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md), I think such migration would be easy for any project.

**Comment by vilchik-elena** [comment]
Changing this ticket from a new rule to a enhancement of our code base

**Comment by vilchik-elena** [comment]
Removing milestone as it has no functional impact
