### ISSUE TITLE
is there way to set the severity for all rules to warn instead of error?

### ISSUE THREAD

**Issue by Ganesh1991** [SonarSource/eslint-plugin-sonarjs#283]
**We are trying to integrate eslint-plugin-sonarjs into one of our existing projects. Currently, it is blocking the build and the CI/CD process due to errors. We are working on resolving the same but we can't solve it at once. is there any option 
to set the severity for all rules to warn?**

**eslint-plugin-sonarjs version:** 0.9.1<br>
**eslint version:** 5.14.1<br>

**Comment by Anuovec** [comment]
https://eslint.org/docs/2.13.1/user-guide/configuring#configuring-rules

Yes, you can specify project specific configuration and change any rule you need

**Comment by thekidnamedkd** [comment]
This doesn't seem to work for `"foo-plugin/recommended" : "warn"` does it? I'd like a quick on/off switch for a whole rule set when it comes to local dev environment, but seems like the docs here only indicate override working on a rule by rule basis within the path. Any thoughts without manually rewriting/replacing the reference files?

**Comment by vilchik-elena** [comment]
relates to https://github.com/SonarSource/eslint-plugin-sonarjs/issues/166

**Comment by vilchik-elena** [comment]
found this https://github.com/bfanger/eslint-plugin-only-warn, may be it's something you need

**Comment by Anuovec** [comment]
That is currently impossible.

Maybe putting `/* eslint-disable */` at the top of the file would help. Or putting the whole codebase in eslint ignore.

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-14](https://sonarsource.atlassian.net/browse/ESLINTJS-14)
