### ISSUE TITLE
prefer-immediate-return disallows function name inference

### ISSUE THREAD

**Issue by slikts** [SonarSource/eslint-plugin-sonarjs#293]
**Feature request**

This should be a valid pattern:
```js
const makeFooHandler = () => {
  const fooHandler = () => {
    //
  }
  return fooHandler
}
```
The returned function's `.name` in this example is inferred to `fooHandler` and makes it easy to recognise in a call stack.

The [`prefer-immediate-return`][1] rule "fixes" this example by returning an anonymous function:
```js
const makeFooHandler = () => {
  return () => {
    //
  }
}
```

The rule should make an exception for named functions since otherwise it's actually changing the semantics and can even change runtime behavior if anything is relying on the `.name` property.

[1]: https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/prefer-immediate-return.md

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-17](https://sonarsource.atlassian.net/browse/ESLINTJS-17)
