### ISSUE TITLE
no-one-iteration-loop is obsolete, recommend eslint built-in rule instead

### ISSUE THREAD

**Issue by lostfictions** [SonarSource/eslint-plugin-sonarjs#317]
**I want to provide the following feedback.**

`no-one-iteration-loop` already exists in the eslint built-in rules under the name [`no-unreachable-loop`](https://eslint.org/docs/rules/no-unreachable-loop), introduced in eslint 7.3.0 (June 2020). `no-one-iteration-loop` should probably be deprecated in favour of the built-in rule to avoid confusion and duplicate warnings.

**Rule key:** `no-one-iteration-loop`

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-18](https://sonarsource.atlassian.net/browse/ESLINTJS-18)
