### ISSUE TITLE
Is all the SonarJs rules (100+ rules) available in eslint-plugin-sonarjs?

### ISSUE THREAD

**Issue by shezhangzhang** [SonarSource/eslint-plugin-sonarjs#327]
**I want to request a feature.**

It seems like there are only 32 rules in eslint-plugin-sonarjs now. Will all the SonarJs rules (100+ rules) available in eslint-plugin-sonarjs?

**Another question:**
eslint-plugin-sonarjs surpport frontend frameworks ? (such as js/ts in vue or react)

**Comment by huineng** [comment]
This is indeed annoying, i lint my project before pushing to sonar, but i still have to check our sonar website to check items not revealed but the plugin .. just a few examples

```
Local variable and function parameter names should comply with a naming convention

Union types should not have too many elements

Functions should use "return" consistently

and several more
```

thanks

**Comment by vilchik-elena** [comment]
@huineng why do you use this plugin if you use sonar?

**Comment by huineng** [comment]
hi thanks, well it's simply not efficient to have clean code on local , then to push to git and build your complete package via ci/cd , then to discover you got some code smell , then to fix that on local and do that whole CI/CD all over again.

Sonar is also being used as a management tool and the greener you get in sonar, the better. So better to prevent it before it ends up there.

thanks

**Comment by vilchik-elena** [comment]
Then you better enable SonarLint IDE plugin and learn about issues asap while coding (VScode or Intellij). You can have connected mode there to sync everything with your sonar setup (rules activation, issues won't fixes, etc).

Do you use other ESLint rules or only eslint-plugin-sonarjs?

So my recommendation is to simplify your life and stop using eslint directly, just through sonar.

**Comment by isChenKan** [comment]
> Then you better enable SonarLint IDE plugin and learn about issues asap while coding (VScode or Intellij). You can have connected mode there to sync everything with your sonar setup (rules activation, issues won't fixes, etc).
> 
> Do you use other ESLint rules or only eslint-plugin-sonarjs?
> 
> So my recommendation is to simplify your life and stop using eslint directly, just through sonar.

SonarLint vscode plugin need jvm (java environment...) to setup. Which is not friendly to frontend developers.😔
We already has CI/CD with sonar cloud service, but our demand is to use it in locally. Because the CI/CD workflow is far away from local development. So I want to use eslint-plugin-sonarjs to do this, But things are not as good as I imagined.😭

**Comment by vilchik-elena** [comment]
Indeed SonarLint needs java but it will install it and manage by itself.

**Comment by isChenKan** [comment]
> 

yeah...I got this error message:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/26793777/154931970-6a3e6c6a-24a5-4e79-b08b-f0854ae2f78d.png">

**Comment by saberduck** [comment]
@isChenKan so, does it work once you click the button? it should be really smooth, and if it's not, we would love to hear why?

**Comment by huineng** [comment]
thanks, i could install the sonarlint after manually installing java jre, but at the end for the moment i'm not going to use it.
I got several other plugins like prettier and my own custom rules, the few i was missing from sonar , i could add them to my eslintrc.

Maybe a bit complicated would be the fact i have a mono repo with 3 sonar properties files.. this is a bit cumbersome to set up (adding multiple workspaces etc) and so for the few lines i might have in sonar, i manage it 

I think though if you have a fresh new project, sonarlint would be a very good option 

thanks

**Comment by saberduck** [comment]
@huineng just fyi, SonarLint doesn't care about `sonar-project.properties` files, they are only used in your CI scan

**Comment by isChenKan** [comment]
@vilchik-elena @saberduck 
**Summarize**
So the only way to sync my sonar cloud rules to local is to install the vscode sonarlint plugin? And using eslint-plugin-sonarjs  is impossible.

**Comment by vilchik-elena** [comment]
@shezhangzhang yeah, I confirm.

**Comment by shezhangzhang** [comment]
> 
@vilchik-elena Thank you. 👍
