### ISSUE TITLE
sonarjs/cognitive-complexity not being detected 

### ISSUE THREAD

**Issue by mikeharrison-selfridges** [SonarSource/eslint-plugin-sonarjs#356]
**I want to report a bug.**

The `sonarjs/cognitive-complexity` rule is not being detected inside of my code editor. It is only being caught on the Sonar report 
![Screenshot 2022-06-07 at 09 43 21](https://user-images.githubusercontent.com/104090089/172337067-662e4bbc-af24-4433-8c78-7a1233953f4e.png)

**eslint-plugin-sonarjs version:** ^0.13.0<br>
**eslint version:** ^7.32.0<br>
**Node.js version:** v16.15.0<br>

**Rule key:** sonarjs/cognitive-complexity

**Comment by vilchik-elena** [comment]
@mikeharrison-selfridges are you aware of [SonarLint](https://www.sonarlint.org/) plugin? Are you using VSCode?

Are you sure you have the same parameter?

Why are you using Sonar along with ESLint?

**Comment by akegvd** [comment]
+1 I got that too.
and I think it should be the same behavior.

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-23](https://sonarsource.atlassian.net/browse/ESLINTJS-23)
