### ISSUE TITLE
Replace deprecated license for the project

### ISSUE THREAD

**Issue by mcmxcdev** [SonarSource/eslint-plugin-sonarjs#392]
**I want to request a feature.**

**Reproducer**

We recently started using https://socket.dev/ as part of our dependencies maintenance and it detected the use of the deprecated license `LGPL-3.0`

See more: https://socket.dev/npm/package/eslint-plugin-sonarjs/overview/0.18.0

Official source regarding deprecation of the license: https://spdx.org/licenses/LGPL-3.0.html

**Expected behavior**

Package uses valid license

**Comment by victor-diez-sonarsource** [comment]
Thanks @mcmxcdev,

we are aware of this and will be updated in the next release.

Cheers
