### ISSUE TITLE
no-duplicate-string ignoreStrings feature

### ISSUE THREAD

**Issue by gusttav-lang** [SonarSource/eslint-plugin-sonarjs#401]
Feature suggestions: add a option in `no-duplicate-string` which recieves a string array with ignored keywords. One situation that it would be useful:
```
const res = await fetch(
      "someAPI",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
    );
```
If we have many api calls in the file, the `"application/json"` will trigger the rule. 

**Rule key: no-duplicate-string**

**Comment by victor-diez-sonarsource** [comment]
Thanks for raising this. Sounds like a good improvement.
