### ISSUE TITLE
Rule: Setters should not return values

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/eslint-plugin-sonarjs#42]
[RSPEC-2432](https://jira.sonarsource.com/browse/RSPEC-2432)

**Comment by EvgenyOrekhov** [comment]
It looks like we'll have this rule in the core: https://github.com/eslint/eslint/issues/12285.

**Comment by vilchik-elena** [comment]
Thanks for letting know

**Comment by EvgenyOrekhov** [comment]
It's landed: https://eslint.org/docs/rules/no-setter-return.
