### ISSUE TITLE
Rule: CSS files should not be empty  

### ISSUE THREAD

**Issue by dnlmelo** [SonarSource/eslint-plugin-sonarjs#436]
**I want to request a feature.**

CSS files should not be empty

Please, add this rule. I have looking for something like, but not found

**Comment by yassin-kammoun-sonarsource** [comment]
Dear @dnlmelo,

Thank you for your valuable feedback!

It appears there may be a slight misunderstanding. This project is specifically focused on a subset of SonarJS rules for JavaScript/TypeScript, delivered through an ESLint plugin. Unfortunately, it does not encompass CSS.

However, I'd like to point out that [SonarJS](https://github.com/SonarSource/SonarJS) is a comprehensive code analyzer for JavaScript, TypeScript, and also CSS. The rule you're seeking, namely that CSS files should not be empty ([S4667](https://rules.sonarsource.com/css/RSPEC-4667/)), is provided by SonarJS.

To leverage this rule directly from your IDE, I recommend using [SonarLint](https://www.sonarsource.com/products/sonarlint/). It's a complimentary IDE plugin that offers linting for several languages, including CSS.

I hope this information is helpful!
