### ISSUE TITLE
Unable to open http://redirect.sonarsource.com/doc/cognitive-complexity.html from https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md

### ISSUE THREAD

**Issue by deathemperor** [SonarSource/eslint-plugin-sonarjs#442]
Page closes immediately when opened

**Comment by ilia-kebets-sonarsource** [comment]
Hello @deathemperor, the link should start the download of the `Cognitive_Complexity_Sonar_Guide_2023.pdf` file. With what browser are you attempting to open the link?

**Comment by deathemperor** [comment]
Oh so opening the http://redirect.sonarsource.com/doc/cognitive-complexity.html link I get the download and Chrome (`Version 120.0.6099.234 (Official Build) (arm64)`) shows this
![image](https://github.com/SonarSource/eslint-plugin-sonarjs/assets/4255482/cbd8adf9-23ab-4131-8652-b45d7b7667fb)

Nothing happens when clicking the link on https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md
