### ISSUE TITLE
`prefer-immediate-return`: allow cases where a type hint is used

### ISSUE THREAD

**Issue by djahandarie** [SonarSource/eslint-plugin-sonarjs#448]
We introduced `prefer-immediate-return` in our code-base, but there are some cases where we need to disable it due to an intermediate variable being required in order to add a type hint.

https://github.com/themoeway/yomitan/pull/673/files/7a8612b035e0847ea0f0e2fc6643693c89bc80f4#diff-e4bb820b23e68d43e6d13aadcd5b41599fc008baaadfde3b84ca53caa97acd37R67

I wonder if this case (the intermediate variable having a type hint) could get some sort of blanket exception, as an immediate return is  impossible in this case (unless you do a cast in the return variable, which is unsafe compared to a type hint).

(Just opening this issue so a discussion can be had, I can imagine that this would be hard to implement in reality as detecting TS and JSDoc syntax type hints seems difficult)

**Comment by vdiez** [comment]
Hi @djahandarie,

thanks for reporting this. Can the type hint be added to the function signature instead? We'll discuss internally if we can add this exception. I'll still add this for the next milestone, but not sure if it's actually worth it.

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-35](https://sonarsource.atlassian.net/browse/ESLINTJS-35)
