### ISSUE TITLE
Put `@typescript-eslint/experimental-utils` in dependencies and/or switch to `@typescript-eslint/utils`

### ISSUE THREAD

**Issue by alecmev** [SonarSource/eslint-plugin-sonarjs#450]
`@typescript-eslint/experimental-utils` isn't a thing since `5.62.0`, and nothing else needs it in the project, so I get the following error with `skipLibCheck: false`:

```
node_modules/eslint-plugin-sonarjs/lib/index.d.ts:1:31 - error TS2307: Cannot find module '@typescript-eslint/experimental-utils' or its corresponding type declarations.

1 import type { TSESLint } from '@typescript-eslint/experimental-utils';
```

The least impactful fix is probably to just find-replace all instances of `@typescript-eslint/experimental-utils` with `@typescript-eslint/utils`, as there's a [`5.30.7`](https://www.npmjs.com/package/@typescript-eslint/utils/v/5.30.7) of it too.

**Comment by ilia-kebets-sonarsource** [comment]
Hey @alecmev,

Thank you for your feedback. We will include this in the next release.
