### ISSUE TITLE
`@typescript-eslint/utils` dependency is missing

### ISSUE THREAD

**Issue by Grmiade** [SonarSource/eslint-plugin-sonarjs#456]
We have this error with the `0.25.0` version: `Error: Failed to load plugin 'sonarjs' declared in '.eslintrc » eslint-config-payfit/rules/common/sonarjs': eslint-plugin-sonarjs tried to access @typescript-eslint/utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

`@typescript-eslint/utils` should be declared as a dependency.
See https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/src/rules/no-use-of-empty-return-value.ts#L22 by example.

**Comment by DEVTomatoCake** [comment]
(Also for reference: https://github.com/SonarSource/eslint-plugin-sonarjs/pull/453#issuecomment-2026828275)

**Comment by ericmorand-sonarsource** [comment]
@Grmiade, version 0.25.1 - fixing the issue - was released. Can you give it a try and let us know how it goes?

**Comment by DEVTomatoCake** [comment]
It works for me using the latest version, thanks!
