### ISSUE TITLE
Rule: Dead stores should be removed

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/eslint-plugin-sonarjs#48]
[RSPEC-1854](https://jira.sonarsource.com/browse/RSPEC-1854)

**Comment by vilchik-elena** [comment]
https://github.com/SonarSource/SonarJS/blob/master/eslint-bridge/src/rules/no-dead-store.ts

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-2](https://sonarsource.atlassian.net/browse/ESLINTJS-2)
