### ISSUE TITLE
Rule:  Loop counters should not be assigned to from within the loop body

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/eslint-plugin-sonarjs#49]
[RSPEC-2310](https://jira.sonarsource.com/browse/RSPEC-2310)

**Comment by vilchik-elena** [comment]
https://github.com/SonarSource/SonarJS/blob/master/eslint-bridge/src/rules/updated-loop-counter.ts

**Comment by Wohops** [comment]
This issue has been migrated to Jira. [ESLINTJS-3](https://sonarsource.atlassian.net/browse/ESLINTJS-3)
