### ISSUE TITLE
Plugin do not scan my project and rules are not applied

### ISSUE THREAD

**Issue by AndonMitev** [SonarSource/eslint-plugin-sonarjs#98]
My current version of node is 8.12.0.
I've been successfully installed npm install eslint-plugin-sonarjs, then import at my plugins "sonarjs" located in .eslintrc file, and finally at extends "plugin:sonarjs/recommended" but there are no rules applied to my code from linter.

**Comment by vilchik-elena** [comment]
see SonarSource/SonarJS#1187
